# Form implementation generated from reading ui file '.\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(429, 134)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 411, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.GezichtenUitknippen = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.GezichtenUitknippen.setObjectName("GezichtenUitknippen")
        self.horizontalLayout.addWidget(self.GezichtenUitknippen)
        self.TrainenGezichten = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.TrainenGezichten.setObjectName("TrainenGezichten")
        self.horizontalLayout.addWidget(self.TrainenGezichten)
        self.LijstMaken = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.LijstMaken.setObjectName("LijstMaken")
        self.horizontalLayout.addWidget(self.LijstMaken)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 50, 411, 61))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 409, 59))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionStartGezichtenUitknippen = QtGui.QAction(MainWindow)
        self.actionStartGezichtenUitknippen.setObjectName("actionStartGezichtenUitknippen")
        self.actionStartTrainen = QtGui.QAction(MainWindow)
        self.actionStartTrainen.setObjectName("actionStartTrainen")
        self.actionStartLijstMaken = QtGui.QAction(MainWindow)
        self.actionStartLijstMaken.setObjectName("actionStartLijstMaken")

        self.retranslateUi(MainWindow)
        self.GezichtenUitknippen.clicked.connect(self.actionStartGezichtenUitknippen.trigger) # type: ignore
        self.TrainenGezichten.clicked.connect(self.actionStartTrainen.trigger) # type: ignore
        self.LijstMaken.clicked.connect(self.actionStartLijstMaken.trigger) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.GezichtenUitknippen.setToolTip(_translate("MainWindow", "<html><head/><body><p>Selecteer een map met afbeeldingen waarvan de gezichten moeten uitgeknipt worden. Selecteer een map waar de uitgeknipt gezichten opgelsagen worden.</p></body></html>"))
        self.GezichtenUitknippen.setText(_translate("MainWindow", "Gezichten Uitknippen"))
        self.TrainenGezichten.setToolTip(_translate("MainWindow", "<html><head/><body><p>Train het systeem op gezichten die onderverdeeld zijn in mappen. Importeer of exporteer de gezichtsdata.</p></body></html>"))
        self.TrainenGezichten.setText(_translate("MainWindow", "Trainen op Gezichten"))
        self.LijstMaken.setToolTip(_translate("MainWindow", "<html><head/><body><p>Genereer een aanezigheislijst aan de hand van een fofo of duid de personen in een foto aan.</p></body></html>"))
        self.LijstMaken.setText(_translate("MainWindow", "Aanwezigheidslijst maken"))
        self.actionStartGezichtenUitknippen.setText(_translate("MainWindow", "StartGezichtenUitknippen"))
        self.actionStartTrainen.setText(_translate("MainWindow", "StartTrainen"))
        self.actionStartLijstMaken.setText(_translate("MainWindow", "StartLijstMaken"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
